language: node_js
sudo: false
node_js:
  - '0.10'
install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
before_script:
  - npm install
  - bower install
script: npm run travis
